FROM node:24-slim

ARG SERVICE_NAME
ARG SERVICE_PORT

ENV SERVICE_NAME=${SERVICE_NAME}
ENV PORT=${SERVICE_PORT}
ENV NODE_ENV=development
ARG DB_URL
ENV DB_URL=${DB_URL}

WORKDIR /workspace

RUN sed -i 's|http://deb.debian.org|https://deb.debian.org|g' /etc/apt/sources.list.d/debian.sources \
  && apt-get update -o Acquire::Retries=5 \
  && apt-get install -y openssl libssl-dev \
  && rm -rf /var/lib/apt/lists/* \
  && corepack enable

COPY package.json yarn.lock ./
COPY common/node-service-kit/package.json ./common/node-service-kit/package.json
COPY services/${SERVICE_NAME}/package.json ./services/${SERVICE_NAME}/package.json

RUN corepack yarn install --frozen-lockfile

COPY common/node-service-kit ./common/node-service-kit
COPY services/${SERVICE_NAME} ./services/${SERVICE_NAME}

WORKDIR /workspace/services/${SERVICE_NAME}

RUN if [ -d prisma ]; then npx prisma@6.3.0 generate; fi

EXPOSE ${SERVICE_PORT}

CMD ["sh", "-c", "corepack yarn exec tsx src/server.ts"]
