export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  EMAIL_ACCOUNT_NOT_FOUND: 'EMAIL_ACCOUNT_NOT_FOUND',
  EMAIL_SYNC_FAILED: 'EMAIL_SYNC_FAILED',
  INVALID_PROVIDER: 'INVALID_PROVIDER',
  INVALID_SEQUENCE: 'INVALID_SEQUENCE',
} as const;
